Rails.application.routes.draw do
  get 'categories/show'
  get 'categories/index'
  #get 'users/create'
  #get 'users/new'
  #get 'articles/create'
  #get 'articles/new'
  #get 'users/new'
  #get 'posts/show'
  #get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'articles#index'
  get    '/login',   to: 'sessions#new'
  post '/login' => 'sessions#create'
  get    '/signup',   to: 'users#new'
  post '/signup' => 'users#create'
  get '/logout',  to: 'sessions#destroy'
  get '/add_article' => 'articles#new'
  post '/add_article' => 'articles#create'
  get '/show_article',  to: 'articles#show'
  post '/show_article',  to: 'articles#show'
  get '/by_category',  to: 'categories#show'
  # post '/update_vote' => 'articles#show'
end
